In [61]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os #shuttle
from skimage.io import imread
from skimage.transform import resize

In [62]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [63]:
os.listdir('/content/drive/MyDrive/Data')

['Dog', 'Cat']

to calculate the total

In [64]:
len(os.listdir('/content/drive/MyDrive/Data/Cat'))

85

In [65]:
len(os.listdir('/content/drive/MyDrive/Data/Dog'))

68

To join paths we can use os:

In [66]:
#creating a folder 'catpath' then taking the path'Data' and mention the folder 'Cat' to join
catpath=os.path.join('/content/drive/MyDrive/Data','Cat')
#using for loop to view the imgs, in catpath it is aved as list
for img in os.listdir(catpath):
  print(img)

cat.93.jpg
cat.71.jpg
cat.67.jpg
cat.91.jpg
cat.86.jpg
cat.77.jpg
cat.87.jpg
cat.94.jpg
cat.64.jpg
cat.82.jpg
cat.88.jpg
cat.68.jpg
cat.84.jpg
cat.74.jpg
cat.81.jpg
cat.70.jpg
cat.63.jpg
cat.96.jpg
cat.73.jpg
cat.72.jpg
cat.95.jpg
cat.92.jpg
cat.65.jpg
cat.66.jpg
cat.78.jpg
cat.76.jpg
cat.89.jpg
cat.69.jpg
cat.90.jpg
cat.83.jpg
cat.75.jpg
cat.85.jpg
cat.97.jpg
cat.98.jpg
cat.43.jpg
cat.56.jpg
cat.57.jpg
cat.61.jpg
cat.62.jpg
cat.50.jpg
cat.60.jpg
cat.51.jpg
cat.48.jpg
cat.44.jpg
cat.58.jpg
cat.46.jpg
cat.54.jpg
cat.47.jpg
cat.49.jpg
cat.59.jpg
cat.55.jpg
cat.45.jpg
cat.53.jpg
cat.52.jpg
cat.79.jpg
cat.80.jpg
cat.100.jpg
cat.38.jpg
cat.35.jpg
cat.116.jpg
cat.106.jpg
cat.36.jpg
cat.118.jpg
cat.115.jpg
cat.42.jpg
cat.41.jpg
cat.119.jpg
cat.103.jpg
cat.108.jpg
cat.109.jpg
cat.117.jpg
cat.37.jpg
cat.102.jpg
cat.111.jpg
cat.107.jpg
cat.112.jpg
cat.114.jpg
cat.113.jpg
cat.40.jpg
cat.104.jpg
cat.101.jpg
cat.105.jpg
cat.39.jpg
cat.110.jpg
cat.99.jpg

In [67]:
dogpath = os.path.join('/content/drive/MyDrive/Data','Dog')
for img in os.listdir(dogpath):
  print(img)

dog.20.jpg
dog.36.jpg
dog.34.jpg
dog.12.jpg
dog.22.jpg
dog.28.jpg
dog.26.jpg
dog.31.jpg
dog.35.jpg
dog.32.jpg
dog.23.jpg
dog.18.jpg
dog.11.jpg
dog.17.jpg
dog.16.jpg
dog.15.jpg
dog.33.jpg
dog.21.jpg
dog.14.jpg
dog.24.jpg
dog.30.jpg
dog.2.jpg
dog.1.jpg
dog.3.jpg
dog.25.jpg
dog.29.jpg
dog.10.jpg
dog.27.jpg
dog.38.jpg
dog.37.jpg
dog.19.jpg
dog.13.jpg
dog.54.jpg
dog.55.jpg
dog.43.jpg
dog.61.jpg
dog.46.jpg
dog.41.jpg
dog.50.jpg
dog.51.jpg
dog.57.jpg
dog.45.jpg
dog.4.jpg
dog.60.jpg
dog.49.jpg
dog.44.jpg
dog.53.jpg
dog.42.jpg
dog.56.jpg
dog.40.jpg
dog.5.jpg
dog.63.jpg
dog.48.jpg
dog.6.jpg
dog.58.jpg
dog.62.jpg
dog.65.jpg
dog.64.jpg
dog.47.jpg
dog.52.jpg
dog.59.jpg
dog.39.jpg
dog.68.jpg
dog.9.jpg
dog.7.jpg
dog.8.jpg
dog.66.jpg
dog.67.jpg

In [68]:
flatten_data = [] #to collect input
target_data = []  #to to collect output
datadir = '/content/drive/MyDrive/Data'
categories=['Dog','Cat'] #as per the listed directory we need to specify the dog and cat in this list

In [69]:
for i in categories: #i=Dog
  print("Loading Categories")
  path=os.path.join(datadir,i)
  for img in os.listdir(path):
    img_arr = imread(os.path.join(path,img))
    img_resize=resize(img_arr,(150,150,3))
    flatten_data.append(img_resize.flatten())
    target_data.append(categories.index(i))

  print("Loaded Completed")

Loading Categories
Loaded Completed
Loading Categories
Loaded Completed

In [70]:
flat_data = np.array(flatten_data)
target_data = np.array(target_data)
#150*150*3 = 67500 cols

In [71]:
df=pd.DataFrame(flat_data)
df

,0,1,2,3,4,5,6,7,8,9,...,67490,67491,67492,67493,67494,67495,67496,67497,67498,67499
0,0.592301,0.636024,0.467658,0.643088,0.689688,0.504767,0.654429,0.701192,0.512705,0.689096,...,0.484030,0.494937,0.492173,0.343318,0.521991,0.519431,0.370331,0.564989,0.571310,0.419112
1,0.616294,0.624137,0.620216,0.618088,0.625932,0.622010,0.563202,0.571045,0.567123,0.517724,...,0.256033,0.295432,0.279745,0.232687,0.289965,0.274279,0.227220,0.284515,0.268829,0.221770
2,0.143728,0.285369,0.145331,0.117835,0.258291,0.131645,0.113765,0.264625,0.134820,0.117743,...,0.168116,0.222354,0.353994,0.184998,0.275889,0.436623,0.259036,0.286613,0.465398,0.285433
3,0.301846,0.556748,0.776355,0.299352,0.554254,0.773862,0.296074,0.550453,0.772675,0.300729,...,0.070725,0.629045,0.249300,0.084594,0.632379,0.250166,0.091354,0.632379,0.249008,0.093671
4,0.162867,0.161325,0.192789,0.088525,0.085070,0.095780,0.138907,0.127494,0.119424,0.106875,...,0.491688,0.642948,0.537585,0.517183,0.604152,0.494363,0.491669,0.543700,0.444245,0.427904
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,0.281699,0.995425,0.999346,0.281699,0.995425,0.999346,0.281699,0.995425,0.999346,0.281569,...,0.975382,0.677381,0.997971,0.993252,0.674711,0.988845,0.975943,0.709319,0.992365,0.986100
149,0.408366,0.376993,0.333856,0.431765,0.400393,0.357255,0.500325,0.468953,0.425815,0.478301,...,0.124019,0.832719,0.695464,0.138601,0.849192,0.708016,0.158996,0.850358,0.709182,0.165814
150,0.061081,0.065003,0.072846,0.061081,0.065003,0.072846,0.061143,0.065064,0.072907,0.065390,...,0.178124,0.283956,0.247814,0.211177,0.326057,0.293775,0.281719,0.346491,0.314406,0.306091
151,0.654589,0.092548,0.203156,0.643521,0.093398,0.199501,0.633144,0.093794,0.195976,0.627333,...,0.196421,0.644119,0.166650,0.215340,0.686256,0.145864,0.234624,0.698753,0.139866,0.235372
152,0.682918,0.659389,0.659388,0.662338,0.641749,0.632928,0.651718,0.632111,0.620346,0.655147,...,0.364115,0.454645,0.332832,0.243040,0.210892,0.097412,0.041618,0.135869,0.034884,0.019520

In [72]:
df['target']=target_data
df

,0,1,2,3,4,5,6,7,8,9,...,67491,67492,67493,67494,67495,67496,67497,67498,67499,target
0,0.592301,0.636024,0.467658,0.643088,0.689688,0.504767,0.654429,0.701192,0.512705,0.689096,...,0.494937,0.492173,0.343318,0.521991,0.519431,0.370331,0.564989,0.571310,0.419112,0
1,0.616294,0.624137,0.620216,0.618088,0.625932,0.622010,0.563202,0.571045,0.567123,0.517724,...,0.295432,0.279745,0.232687,0.289965,0.274279,0.227220,0.284515,0.268829,0.221770,0
2,0.143728,0.285369,0.145331,0.117835,0.258291,0.131645,0.113765,0.264625,0.134820,0.117743,...,0.222354,0.353994,0.184998,0.275889,0.436623,0.259036,0.286613,0.465398,0.285433,0
3,0.301846,0.556748,0.776355,0.299352,0.554254,0.773862,0.296074,0.550453,0.772675,0.300729,...,0.629045,0.249300,0.084594,0.632379,0.250166,0.091354,0.632379,0.249008,0.093671,0
4,0.162867,0.161325,0.192789,0.088525,0.085070,0.095780,0.138907,0.127494,0.119424,0.106875,...,0.642948,0.537585,0.517183,0.604152,0.494363,0.491669,0.543700,0.444245,0.427904,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,0.281699,0.995425,0.999346,0.281699,0.995425,0.999346,0.281699,0.995425,0.999346,0.281569,...,0.677381,0.997971,0.993252,0.674711,0.988845,0.975943,0.709319,0.992365,0.986100,1
149,0.408366,0.376993,0.333856,0.431765,0.400393,0.357255,0.500325,0.468953,0.425815,0.478301,...,0.832719,0.695464,0.138601,0.849192,0.708016,0.158996,0.850358,0.709182,0.165814,1
150,0.061081,0.065003,0.072846,0.061081,0.065003,0.072846,0.061143,0.065064,0.072907,0.065390,...,0.283956,0.247814,0.211177,0.326057,0.293775,0.281719,0.346491,0.314406,0.306091,1
151,0.654589,0.092548,0.203156,0.643521,0.093398,0.199501,0.633144,0.093794,0.195976,0.627333,...,0.644119,0.166650,0.215340,0.686256,0.145864,0.234624,0.698753,0.139866,0.235372,1
152,0.682918,0.659389,0.659388,0.662338,0.641749,0.632928,0.651718,0.632111,0.620346,0.655147,...,0.454645,0.332832,0.243040,0.210892,0.097412,0.041618,0.135869,0.034884,0.019520,1

In [73]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [74]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [75]:
from sklearn.svm import SVC
model = SVC()
model.fit(x_train,y_train)

SVC()

In [76]:
y_pred = model.predict(x_test)
y_pred

array([0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1])

In [77]:
from sklearn.metrics import classification_report,accuracy_score
acc = accuracy_score(y_test,y_pred)
acc

0.45161290322580644

prediction

In [81]:
img1='/content/drive/MyDrive/Data/pexels-pixabay-104827.jpg'
img1=imread(img1)
res=resize(img1,(150,150,3)).reshape(1,-1)
pred=model.predict(res)
pred

array([1])